content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
          I started this project as a way of learning <mark>React</mark> and it has since grown into a fully-fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by digging holes and making game-changing products like the *not a flamethrower*
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard and I play my part in making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |
          During my time at Harvard, I learned most of my key skills that I have taken through my career, such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at university and learned a lot about a healthy work-life balance. I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club*, taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Blog Posts
    layout: list
    content: [] # Empty placeholder for blog posts

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in networks and software engineering, some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
